source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Titch' do
    pod 'Alamofire', '~> 3.4'
    pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
    pod 'Toast-Swift', '~> 1.3.0'
end