source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target "Titch" do 
    pod 'Material', '~> 1.0'
    pod 'Alamofire', '~> 3.4'
    pod 'AlamofireImage', '~> 2.0'
    pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
    pod 'Toast-Swift', '~> 1.3.0'
end